### ISSUE TITLE
dropping DB breaks open iterators (other objects?)

### ISSUE THREAD

**Issue by rob-solana** [rust-rocksdb/rust-rocksdb#234] opened 2018-12-07 18:24 UTC
test code:
```rust
extern crate rocksdb;
use rocksdb::{Options, DB};

fn main() {
    let _ignored = DB::destroy(&Options::default(), "test_db");

    let mut iter = {
        let mut options = Options::default();
        options.create_if_missing(true);

        let db = DB::open(&options, "test_db").unwrap();

        for i in 0..100 {
            db.put(&[i], &[i]).expect(&format!("writing {} failed", i));
        }
        db.raw_iterator()
    };

    // iterate
    iter.seek_to_first();
    while iter.valid() {
        println!("Saw {:?} {:?}", iter.key(), iter.value());
        iter.next();
    }
    // crashes at some point
}

```

**expected behavior:** successful run
**observed behavior:** segfault, pthread error, other aborts, depending on timing

It'd be nice for rocksdb to support this use case so that rust Iterators can be written without underbar _members, e.g.:

```
struct FooIterator {
    db_iterator: DBRawIterator,

    // this _db_ledger member must be lower in the struct to prevent a crash
    // when the db_iterator member above is dropped.
    // _db_ledger is unused, but dropping _db_ledger results in a broken db_iterator
    // you have to hold the database open in order to iterate over it, and in order
    // for db_iterator to be able to run Drop
    _db: DB,
}

impl Iterator for FooIterator {
   type Item = ...
```

**Comment by iSynaptic** [comment] 2018-12-07 18:37
Is this even supported by the underlying RocksDB library, eg. closing the database and continuing to use open iterators? I'm not sure this is something that can be supported.  Once the `DB` is dropped, the [underlying database is closed](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/src/db.rs#L1250), and I believe that invalidates open iterators. If anything, I might suggest we add a lifetime to iterators to ensure they cannot outlive a `DB`.

**Comment by iSynaptic** [comment] 2018-12-07 19:50
I think the "rust-y" approach, as you put it, would be to wrap the `DB` in a smart pointer such as `Rc<T>` or `Arc<T>` to manage the lifetime of the underlying `DB` struct.  Those smart pointer types implement `Clone`, allowing you to have multiple owned smart-pointers to the `DB` struct.  Implementing `Clone` on the `DB` struct would be dangerous, since it manages the underlying `unsafe` C pointer from the core RocksDB library.  I think where this library failed was allowing a program to compile where the iterator could outlive the `DB`, causing the segfault.  I'll log that as a different issue and close this issue since I think this behavior is by design.

**Closed by iSynaptic** 2018-12-07 19:50 UTC
