### ISSUE TITLE
streamlining DB api with regard to CFs

### ISSUE THREAD

**Issue by rrichardson** [rust-rocksdb/rust-rocksdb#145] opened 2017-10-19 18:44 UTC
This is a bit of a follow-on from #144  but is different enough in scope

The native RocksDB column family API is a bit clunky and seems like an after thought.  If users of rust-rocksdb prefer it this way, then that's fine, you can stop reading now.  

If you're still with me,  I am thinking that we can remove all PIGMED operations and remove the *_cf.  The way we do this is make ColumnFamily the source for PIGMED operations.  Or, we can shorten "ColumnFamily" to "Table" .   So the API would look something like : 

```
DB::open() -> DBResult   //which would enumerate and use all CFs by default
DB.get_table(cf_name: string) -> TableResult . // it would fetch the named table if it exists
DB.get_default_table() -> TableResult // if the user is living in the dark ages, use the default table

Table.put(key, val) 
Table.get(key)...
...
```

I have a crate [rocks-cache](https://github.com/QuiverMedia/rocks-cache/blob/master/src/lib.rs) that implements this API and it works quite nicely. We've been using it at work for a bit.

**Comment by vmx** [comment] 2017-10-19 21:38
I like the idea of making the Column Family stuff easier to use. Though I don't have good ideas how to do it :)

How would `DB::open()` know about the existing Column Families? In RocksDB you need to pass in their name and options.

**Comment by rrichardson** [comment] 2017-10-19 21:50
There is a  DB::list_cf  (rocksdb_list_column_families in the C API) function which just takes a path and lists all of the column families.  It actually represents one of my annoyances with the original API.   There is a function to enumerate column families, but when you create a DB object, you have to explicitly enumerate the CFs.  I can kind of see why.. but I still don't like it. 

In rocks-cache I have a Builder style object which enumerates all CFs, and then lets you add attitional ones if you like, and it will load all of these into the RocksDB::DB  (this requires a &mut DB)  then after you build() it returns a DB object which doesn't allow mutation of CFs, that way you don't need a &mut DB.

**Comment by vmx** [comment] 2017-10-19 22:10
The problem is that with `ListColumnFamilies()` you'll only get the names, but not the options. So your application needs to keep the options somewhere and then it's easy to store the name with it as well.

**Comment by rrichardson** [comment] 2017-10-19 22:40
I see your point. 

It seems to me that the problem is that you need to supply the options twice.  Persisting them to disk with the CF seems like the only safe thing to do.

**Comment by vmx** [comment] 2017-10-19 22:53
I think the original post of issue https://github.com/facebook/rocksdb/issues/1055 sums up the problem with RocksDBs Column Family API pretty nicely.

**Comment by rrichardson** [comment] 2017-10-19 23:32
What I get from that is their excuse for why they designed their API so poorly (needing to associate options with CFs)  should actually be the exact reason to design an API that is more ergonomic and also foolproof.

**Comment by vmx** [comment] 2017-10-19 23:52
While reading the RocksDB source I found: https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File. Though one problem surely are the "unsupported options".

**Comment by vmx** [comment] 2017-10-20 21:24
As there is the `create_missing_column_families` option how about an API like this:

```Rust
let cf1_options = ColumnFamilyOptions::new("cf1_name");
cf1_options.set_max_write_buffer_number(16);

let options = Options::default();
options.set_column_families(vec![cf1_options])

// `create_missing_column_families = true` is default
let db = DB::open(&db_opts, "path/for/rocksdb/storage_with_cfs");

let cf1 = db.get_cf("cf1_name");
cf1.put("hello", "world");
```

**Comment by rrichardson** [comment] 2017-10-21 00:33
That looks good to me.   I think that'd be an excellent place to start. I'll have a look at #136 as well. 

After that, 
We might want to experiment with paramaterizing the ColumnFamily by key and value types. 
The hard part is that the types would need to be  Deserialize<'a> + Serialize which is a bit of a pain. 
The neat thing is that we could associate MergeOperators with the CFs and ensure that they work with the types. 

Thoughts?

**Comment by vmx** [comment] 2017-10-22 19:32
@rrichardson I don't understand what you mean with "paramaterizing the ColumnFamily by key and value types".

**Comment by rrichardson** [comment] 2017-10-22 20:20
something like :
```
impl<K: Serialize + Deserialize, V: Serialize + Deserialize>   ColumnFamily<K, V> {
  fn put(K, V) -> Result {}
  fn get(K, V) -> Result {) 
  fn merge(K, V) -> Result {}
}
```

so we could have type safe serialization and deserialization as well as merging that could support a specific set of operations (sets, counters, etc)

**Comment by vmx** [comment] 2017-10-22 20:28
Oh, I see. That would be pretty cool.

**Comment by iSynaptic** [comment] 2019-02-04 13:22
It's been over a year since this was discussed. Suggesting that we close.

I share your frustration with the abstractions.  Much of the ergonomics when using column families is no doubt a result of column families being a later addition to underlying library.  However, I think the direction with this library has historically always been a thin Rust wrapper over the underlying RocksDB.  Drastically changing the Rust API abstractions in comparison to the native RocksDB abstractions would require a greater documentation burden because of how different the libraries would become.  Creating an opinionated wrapper around RocksDB I think should be pushed into a different crate, using this one as a dependency.

**Comment by vmx** [comment] 2019-02-04 13:53
As it's been over a year, I don't remember the details. Though IIRC it would be quite difficult to create a new crate which just chnages how column family work, without being essentially a fork. I'd still believe that a simpler API is desirable, but as I don't have any time for helping out at the moment, I'm OK with having it closed as "won't fix".

**Comment by iSynaptic** [comment] 2019-02-04 17:08
@vmx Sounds good. I've been spending a lot of time trying to improve the ergonomics of the API while staying true to the underlying API (see #253 and #255).  I'm going to close this, but I'm open to more suggestions on how we can improve the ergonomics of the API.

I've got another PR planned to make better use of traits for the definition of "PIGMED" operations.  It will simplify the existing functionality as well as make it easier to implement #144, #178, and we _might_ be able to implement *some* of the traits on `ColumnFamily`, getting some of the ergonomics asked for here.

**Closed by iSynaptic** 2019-02-04 17:08 UTC
Labels: enhancement
