### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

### ISSUE THREAD

**Issue by m-yahya** [rust-rocksdb/rust-rocksdb#714] opened 2022-12-01 12:48 UTC
I'm trying to compile substrate-node-template by following along the instructions listed [here](https://docs.substrate.io/install/linux/).
The complete error message is: 

```
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/substrate-node-template/target/release/build/librocksdb-sys-aabd480a2f3b76e0/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident', /.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**OS**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic              
Kernel: Linux 5.19.0-23-generic
Architecture: x86-64
```

**Installed dependencies**

```
llvm is already the newest version (1:16.0-57~exp1~20220923135553.1).
clang is already the newest version (1:16.0-57~exp1~20220923135553.1).

ldd (Ubuntu GLIBC 2.36-0ubuntu4) 2.36

gcc version 12.2.0 (Ubuntu 12.2.0-3ubuntu1) 

make is already the newest version (4.3-4.1build1).
clang is already the newest version (1:16.0-57~exp1~20220923135553.1).
pkg-config is already the newest version (0.29.2-1ubuntu3).
libssl-dev is already the newest version (3.0.5-2ubuntu2).

build-essential is already the newest version (12.9ubuntu3).



git is already the newest version (1:2.37.2-1ubuntu1.1).
curl is already the newest version (7.85.0-1ubuntu0.1).
libudev-dev is already the newest version (251.4-1ubuntu7).
protobuf-compiler is already the newest version (3.12.4-1ubuntu7).

rustc 1.66.0-nightly (5c8bff74b 2022-10-21)

Default host: x86_64-unknown-linux-gnu
rustup home:  /home/yahya/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2022-10-22-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.67.0-nightly (e0098a5cc 2022-11-29)
```

Steps to reproduce:

```
$ git clone https://github.com/substrate-developer-hub/substrate-node-template
$ cd substrate-node-template
$ cargo build --release
```

**Comment by aleksuss** [comment] 2022-12-01 12:58
I think it's a duplicate of #713

**Closed by aleksuss** 2022-12-01 12:58 UTC
