### ISSUE TITLE
Support for transaction and GetForUpdate?

### ISSUE THREAD

**Issue by qinix** [rust-rocksdb/rust-rocksdb#178] opened 2018-03-31 04:27 UTC
https://github.com/facebook/rocksdb/wiki/Transactions#read-write-conflict-detection

**Comment by iSynaptic** [comment] 2019-02-04 10:55
Perhaps coming in #250

**Comment by iSynaptic** [comment] 2019-03-16 18:25
Closing this as a duplicate of #144.

**Closed by iSynaptic** 2019-03-16 18:25 UTC
Labels: enhancement
